version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ghcr.io/ParisTxGroup/icdot_production_django
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/euris-ca.pem
    volumes:
      - /usr/share/ca-certificates/cloudsante/euris-ca.crt:/etc/ssl/certs/euris-ca.pem:ro
    command: /start
    ports:
      - 0.0.0.0:80:5000
    extra_hosts:
      - host.docker.internal:postgres

  redis:
    image: redis:6
